language: python
python:
  - "3.4"

install:
  - nvm install 10.16

script: node ./src/index.js --input_file ./tests/simple/events.json --window_size 10 --output_file ./tests/simple/output.json && 
  python tests/index.test.py